version: '3.1'

services:
  mysql:
    image: mysql:5.7.21
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=AOS_1895
    ports:
      - 3306:3306
      - 10049:10049
    volumes: 
      - mysql-data:/var/lib/mysql
      
volumes: 
  mysql-data:
